API_COMPONENTS_SHOW = "/api/components/show"

API_PROJECTS_BULK_DELETE = "/api/projects/bulk_delete"
API_PROJECTS_SEARCH = "/api/projects/search"
API_PROJECTS_CREATE = "/api/projects/create"
API_PROJECTS_DELETE = "/api/projects/delete"
API_PROJECTS_UPDATE_VISIBILITY = "/api/projects/update_visibility"
API_PROJECTS_UPDATE_KEY = "/api/projects/update_key"
API_PROJECTS_EXPORT_FINDINGS = "/api/projects/export_findings"
API_PROJECTS_LICENSE_USAGE = "/api/projects/license_usage"
API_PROJECTS_UPDATE_DEFAULT_VISIBILITY = "/api/projects/update_default_visibility"

API_APPLICATIONS_ADD_PROJECT = "/api/applications/add_project"
API_APPLICATIONS_REMOVE_PROJECT = "/api/applications/remove_project"
API_APPLICATIONS_SHOW = "/api/applications/show"
API_APPLICATIONS_CREATE = "/api/applications/create"
API_APPLICATIONS_DELETE = "/api/applications/delete"
API_APPLICATIONS_UPDATE = "/api/applications/update"
API_APPLICATIONS_CREATE_BRANCH = "/api/applications/create_branch"
API_APPLICATIONS_DELETE_BRANCH = "/api/applications/delete_branch"
API_APPLICATIONS_UPDATE_BRANCH = "/api/applications/update_branch"
API_APPLICATIONS_SET_TAGS = "/api/applications/set_tags"

API_USERS_SEARCH = "/api/users/search"
API_USERS_CREATE = "/api/users/create"
API_USERS_UPDATE = "/api/users/update"
API_USERS_ANONYMIZE = "/api/users/anonymize"
API_USERS_CHANGE_PASSWORD = "/api/users/change_password"
API_USERS_GROUPS = "/api/users/groups"
API_USERS_DEACTIVATE = "/api/users/deactivate"
API_USERS_UPDATE_LOGIN = "/api/users/update_login"
API_USERS_DISMISS_NOTICE = "/api/users/dismiss_notice"
API_USERS_UPDATE_IDENTITY = "/api/users/update_identity_provider"

API_USER_GROUPS_SEARCH = "/api/user_groups/search"
API_USER_GROUPS_CREATE = "/api/user_groups/create"
API_USER_GROUPS_DELETE = "/api/user_groups/delete"
API_USER_GROUPS_UPDATE = "/api/user_groups/update"
API_USER_GROUPS_USERS = "/api/user_groups/users"
API_USER_GROUPS_ADD_USER = "/api/user_groups/add_user"
API_USER_GROUPS_REMOVE_USER = "/api/user_groups/remove_user"

API_PERMISSIONS_ADD_GROUP = "/api/permissions/add_group"
API_PERMISSIONS_REMOVE_GROUP = "/api/permissions/remove_group"
API_PERMISSIONS_ADD_USER = "/api/permissions/add_user"
API_PERMISSIONS_REMOVE_USER = "/api/permissions/remove_user"
API_PERMISSIONS_APPLY_TEMPLATE = "/api/permissions/apply_template"
API_PERMISSIONS_ADD_GROUP_TO_TEMPLATE = "/api/permissions/add_group_to_template"
API_PERMISSIONS_ADD_PROJECT_CREATOR_TO_TEMPLATE = "/api/permissions/add_project_creator_to_template"
API_PERMISSIONS_ADD_USER_TO_TEMPLATE = "/api/permissions/add_user_to_template"
API_PERMISSIONS_BULK_APPLY_TEMPLATE = "/api/permissions/bulk_apply_template"
API_PERMISSIONS_CREATE_TEMPLATE = "/api/permissions/create_template"
API_PERMISSIONS_DELETE_TEMPLATE = "/api/permissions/delete_template"
API_PERMISSIONS_REMOVE_GROUP_FROM_TEMPLATE = "/api/permissions/remove_group_from_template"
API_PERMISSIONS_REMOVE_PROJECT_CREATOR_FROM_TEMPLATE = "/api/permissions/remove_project_creator_from_template"
API_PERMISSIONS_REMOVE_USER_FROM_TEMPLATE = "/api/permissions/remove_user_from_template"
API_PERMISSIONS_SEARCH_TEMPLATES = "/api/permissions/search_templates"
API_PERMISSIONS_SET_DEFAULT_TEMPLATE = "/api/permissions/set_default_template"
API_PERMISSIONS_UPDATE_TEMPLATE = "/api/permissions/update_template"
API_PERMISSIONS_USERS = "/api/permissions/users"
API_PERMISSIONS_GROUPS = "/api/permissions/groups"
API_PERMISSIONS_TEMPLATE_USERS = "/api/permissions/template_users"
API_PERMISSIONS_TEMPLATE_GROUPS = "/api/permissions/template_groups"

API_CE_ACTIVITY = "/api/ce/activity"
API_CE_ACTIVITY_STATUS = "/api/ce/activity_status"
API_CE_ANALYSIS_STATUS = "/api/ce/analysis_status"
API_CE_COMPONENT = "/api/ce/component"
API_CE_TASK = "/api/ce/task"

API_MEASURES_COMPONENT = "/api/measures/component"
API_MEASURES_COMPONENT_TREE = "/api/measures/component_tree"
API_MEASURES_SEARCH_HISTORY = "/api/measures/search_history"

API_PROJECT_BRANCHES_LIST = "/api/project_branches/list"
API_PROJECT_BRANCHES_RENAME = "/api/project_branches/rename"
API_PROJECT_BRANCHES_DELETE = "/api/project_branches/delete"
API_PROJECT_BRANCHES_SET_PROTECTION = "/api/project_branches/set_automatic_deletion_protection"

API_PROJECT_DUMP_EXPORT = "/api/project_dump/export"
API_PROJECT_DUMP_IMPORT = "/api/project_dump/import"

API_NOTIFICATIONS_ADD = "/api/notifications/add"
API_NOTIFICATIONS_LIST = "/api/notifications/list"
API_NOTIFICATIONS_REMOVE = "/api/notifications/remove"

API_ISSUES_SEARCH = "/api/issues/search"
API_ISSUES_ASSIGN = "/api/issues/assign"
API_ISSUES_DO_TRANSITION = "/api/issues/do_transition"
API_ISSUES_ADD_COMMENT = "/api/issues/add_comment"
API_ISSUES_EDIT_COMMENT = "/api/issues/edit_comment"
API_ISSUES_DELETE_COMMENT = "/api/issues/delete_comment"
API_ISSUES_SET_SEVERITY = "/api/issues/set_severity"
API_ISSUES_SET_TYPE = "/api/issues/set_type"
API_ISSUES_AUTHORS = "/api/issues/authors"
API_ISSUES_BULK_CHANGE = "/api/issues/bulk_change"
API_ISSUES_CHANGELOG = "/api/issues/changelog"
API_ISSUES_SET_TAGS = "/api/issues/set_tags"
API_ISSUES_TAGS = "/api/issues/tags"

API_PROJECT_LINKS_CREATE = "/api/project_links/create"
API_PROJECT_LINKS_DELETE = "/api/project_links/delete"
API_PROJECT_LINKS_SEARCH = "/api/project_links/search"

API_QUALITYGATES_PROJECT_STATUS = "/api/qualitygates/project_status"
API_QUALITYGATES_LIST = "/api/qualitygates/list"
API_QUALITYGATES_SELECT = "/api/qualitygates/select"
API_QUALITYGATES_DESELECT = "/api/qualitygates/deselect"
API_QUALITYGATES_SHOW = "/api/qualitygates/show"
API_QUALITYGATES_GET_BY_PROJECT = "/api/qualitygates/get_by_project"
API_QUALITYGATES_COPY = "/api/qualitygates/copy"
API_QUALITYGATES_CREATE = "/api/qualitygates/create"
API_QUALITYGATES_CREATE_CONDITION = "/api/qualitygates/create_condition"
API_QUALITYGATES_DELETE_CONDITION = "/api/qualitygates/delete_condition"
API_QUALITYGATES_DESTROY = "/api/qualitygates/destroy"
API_QUALITYGATES_RENAME = "/api/qualitygates/rename"
API_QUALITYGATES_SEARCH = "/api/qualitygates/search"
API_QUALITYGATES_SET_AS_DEFAULT = "/api/qualitygates/set_as_default"
API_QUALITYGATES_UPDATE_CONDITION = "/api/qualitygates/update_condition"
API_QUALITYGATES_ADD_USER = "/api/qualitygates/add_user"
API_QUALITYGATES_ADD_GROUP = "/api/qualitygates/add_group"

API_COMPONTENTS_SHOW = "/api/components/show"
API_COMPONTENTS_SEARCH = "/api/components/search"
API_COMPONTENTS_TREE = "/api/components/tree"

API_RULES_SEARCH = "/api/rules/search"
API_RULES_CREATE = "/api/rules/create"
API_RULES_UPDATE = "/api/rules/update"
API_RULES_DELETE = "/api/rules/delete"
API_RULES_SHOW = "/api/rules/show"
API_RULES_TAGS = "/api/rules/tags"
API_RULES_REPOSITORIES = "/api/rules/repositories"

API_QUALITYPROFILES_ACTIVATE_RULE = "/api/qualityprofiles/activate_rule"
API_QUALITYPROFILES_SEARCH = "/api/qualityprofiles/search"
API_QUALITYPROFILES_DELETE = "/api/qualityprofiles/delete"
API_QUALITYPROFILES_SET_DEFAULT = "/api/qualityprofiles/set_default"
API_QUALITYPROFILES_ADD_PROJECT = "/api/qualityprofiles/add_project"
API_QUALITYPROFILES_REMOVE_PROJECT = "/api/qualityprofiles/remove_project"
API_QUALITYPROFILES_ACTIVATE_RULES = "/api/qualityprofiles/activate_rules"
API_QUALITYPROFILES_BACKUP = "/api/qualityprofiles/backup"
API_QUALITYPROFILES_CHANGE_PARENT = "/api/qualityprofiles/change_parent"
API_QUALITYPROFILES_CHANGELOG = "/api/qualityprofiles/changelog"
API_QUALITYPROFILES_COPY = "/api/qualityprofiles/copy"
API_QUALITYPROFILES_CREATE = "/api/qualityprofiles/create"
API_QUALITYPROFILES_DEACTIVATE_RULE = "/api/qualityprofiles/deactivate_rule"
API_QUALITYPROFILES_DEACTIVATE_RULES = "/api/qualityprofiles/deactivate_rules"
API_QUALITYPROFILES_EXPORT = "/api/qualityprofiles/export"
API_QUALITYPROFILES_EXPORTERS = "/api/qualityprofiles/exporters"
API_QUALITYPROFILES_IMPORTERS = "/api/qualityprofiles/importers"
API_QUALITYPROFILES_INHERITANCE = "/api/qualityprofiles/inheritance"
API_QUALITYPROFILES_PROJECTS = "/api/qualityprofiles/projects"
API_QUALITYPROFILES_RENAME = "/api/qualityprofiles/rename"
API_QUALITYPROFILES_RESTORE = "/api/qualityprofiles/restore"
API_QUALITYPROFILES_ADD_USER = "/api/qualityprofiles/add_user"
API_QUALITYPROFILES_ADD_GROUP = "/api/qualityprofiles/add_group"

API_DUPLICATIONS_SHOW = "/api/duplications/show"

API_PDFREPORT_GET = "/api/pdfreport/get"

API_METRICS_SEARCH = "/api/metrics/search"
API_METRICS_TYPES = "/api/metrics/types"

API_SETTINGS_LIST_DEFINITIONS = "/api/settings/list_definitions"
API_SETTINGS_RESET = "/api/settings/reset"
API_SETTINGS_SET = "/api/settings/set"
API_SETTINGS_VALUES = "/api/settings/values"

API_SOURCES_SCM = "/api/sources/scm"
API_SOURCES_SHOW = "/api/sources/show"
API_SOURCES_RAW = "/api/sources/raw"

API_AUTH_LOGIN = "/api/authentication/login"
API_AUTH_LOGOUT = "/api/authentication/logout"
API_AUTH_VALIDATE = "/api/authentication/validate"

API_FAVORITES_ADD = "/api/favorites/add"
API_FAVORITES_REMOVE = "/api/favorites/remove"
API_FAVORITES_SEARCH = "/api/favorites/search"

API_LANGUAGES_LIST = "/api/languages/list"

API_PROJECT_BADGES_MEASURE = "/api/project_badges/measure"
API_PROJECT_BADGES_QUALITY_GATE = "/api/project_badges/quality_gate"
API_PROJECT_BADGES_TOKEN = "/api/project_badges/token"
API_PROJECT_BADGES_RENEW_TOKEN = "/api/project_badges/renew_token"

API_PROJECT_TAGS_SEARCH = "/api/project_tags/search"
API_PROJECT_TAGS_SET = "/api/project_tags/set"

API_PROJECT_PULL_REQUESTS_DELETE = "/api/project_pull_requests/delete"
API_PROJECT_PULL_REQUESTS_LIST = "/api/project_pull_requests/list"

API_PROJECT_ANALYSES_CREATE_EVENT = "/api/project_analyses/create_event"
API_PROJECT_ANALYSES_DELETE = "/api/project_analyses/delete"
API_PROJECT_ANALYSES_DELETE_EVENT = "/api/project_analyses/delete_event"
API_PROJECT_ANALYSES_SEARCH = "/api/project_analyses/search"
API_PROJECT_ANALYSES_SET_BASELINE = "/api/project_analyses/set_baseline"
API_PROJECT_ANALYSES_UNSET_BASELINE = "/api/project_analyses/unset_baseline"
API_PROJECT_ANALYSES_UPDATE_EVENT = "/api/project_analyses/update_event"

API_SERVER_VERSION = "/api/server/version"

API_USER_TOKENS_GENERATE = "/api/user_tokens/generate"
API_USER_TOKENS_REVOKE = "/api/user_tokens/revoke"
API_USER_TOKENS_SEARCH = "/api/user_tokens/search"

API_WEBHOOKS_CREATE = "/api/webhooks/create"
API_WEBHOOKS_DELETE = "/api/webhooks/delete"
API_WEBHOOKS_DELIVERIES = "/api/webhooks/deliveries"
API_WEBHOOKS_DELIVERY = "/api/webhooks/delivery"
API_WEBHOOKS_LIST = "/api/webhooks/list"
API_WEBHOOKS_UPDATE = "/api/webhooks/update"

API_WEBSERVICES_LIST = "/api/webservices/list"
API_WEBSERVICES_RESPONSE_EXAMPLE = "/api/webservices/response_example"

API_SYSTEM_CHANGE_LOG_LEVEL = "/api/system/change_log_level"
API_SYSTEM_DB_MIGRATION_STATUS = "/api/system/db_migration_status"
API_SYSTEM_HEALTH = "/api/system/health"
API_SYSTEM_LOGS = "/api/system/logs"
API_SYSTEM_MIGRATE_DB = "/api/system/migrate_db"
API_SYSTEM_PING = "/api/system/ping"
API_SYSTEM_RESTART = "/api/system/restart"
API_SYSTEM_STATUS = "/api/system/status"
API_SYSTEM_UPGRADES = "/api/system/upgrades"
API_SYSTEM_INFO = "/api/system/info"

API_PLUGINS_AVAILABLE = "/api/plugins/available"
API_PLUGINS_CANCEL_ALL = "/api/plugins/cancel_all"
API_PLUGINS_INSTALL = "/api/plugins/install"
API_PLUGINS_INSTALLED = "/api/plugins/installed"
API_PLUGINS_PENDING = "/api/plugins/pending"
API_PLUGINS_UNINSTALL = "/api/plugins/uninstall"
API_PLUGINS_UPDATE = "/api/plugins/update"
API_PLUGINS_UPDATES = "/api/plugins/updates"

API_ALM_INTEGRATION_SET_PAT = "/api/alm_integrations/set_pat"
API_ALM_INTEGRATION_SEARCH_BITBUCKETSERVER_REPOS = "/api/alm_integrations/search_bitbucketserver_repos"
API_ALM_INTEGRATION_LIST_BITBUCKETSERVER_PROJECTS = "/api/alm_integrations/list_bitbucketserver_projects"
API_ALM_INTEGRATION_SEARCH_BITBUCKETCLOUD_REPOS = "/api/alm_integrations/search_bitbucketcloud_repos"
API_ALM_INTEGRATION_LIST_AZURE_PROJECTS = "/api/alm_integrations/list_azure_projects"
API_ALM_INTEGRATION_SEARCH_AZURE_REPOS = "/api/alm_integrations/search_azure_repos"
API_ALM_INTEGRATION_SEARCH_GITLAB_REPOS = "/api/alm_integrations/search_gitlab_repos"
API_ALM_INTEGRATION_IMPORT_GITLAB_PROJECT = "/api/alm_integrations/import_gitlab_project"

API_ALM_SETTINGS_LIST = "/api/alm_settings/list"
API_ALM_SETTINGS_DELETE = "/api/alm_settings/delete"
API_ALM_SETTINGS_VALIDATE = "/api/alm_settings/validate"
API_ALM_SETTINGS_LIST_DEFINITIONS = "/api/alm_settings/list_definitions"
API_ALM_SETTINGS_CREATE_GITLAB = "/api/alm_settings/create_gitlab"
API_ALM_SETTINGS_CREATE_GITHUB = "/api/alm_settings/create_github"
API_ALM_SETTINGS_CREATE_BITBUCKET = "/api/alm_settings/create_bitbucket"
API_ALM_SETTINGS_CREATE_BITBUCKETCLOUD = "/api/alm_settings/create_bitbucketcloud"
API_ALM_SETTINGS_CREATE_AZURE = "/api/alm_settings/create_azure"
API_ALM_SETTINGS_UPDATE_GITLAB = "/api/alm_settings/update_gitlab"
API_ALM_SETTINGS_UPDATE_GITHUB = "/api/alm_settings/update_github"
API_ALM_SETTINGS_UPDATE_BITBUCKET = "/api/alm_settings/update_bitbucket"
API_ALM_SETTINGS_UPDATE_BITBUCKETCLOUD = "/api/alm_settings/update_bitbucketcloud"
API_ALM_SETTINGS_UPDATE_AZURE = "/api/alm_settings/update_azure"
API_ALM_SETTINGS_GET_BINDING = "/api/alm_settings/get_binding"
API_ALM_SETTINGS_COUNT_BINDING = "/api/alm_settings/count_binding"
API_ALM_SETTINGS_DELETE_BINDING = "/api/alm_settings/delete_binding"
API_ALM_SETTINGS_SET_GITLAB_BINDING = "/api/alm_settings/set_gitlab_binding"
API_ALM_SETTINGS_SET_GITHUB_BINDING = "/api/alm_settings/set_github_binding"
API_ALM_SETTINGS_SET_BITBUCKET_BINDING = "/api/alm_settings/set_bitbucket_binding"
API_ALM_SETTINGS_SET_BITBUCKETCLOUD_BINDING = "/api/alm_settings/set_bitbucketcloud_binding"
API_ALM_SETTINGS_SET_AZURE_BINDING = "/api/alm_settings/set_azure_binding"


API_APPLICATIONS_UPDATE_BRANCH = "/api/applications/update_branch"
API_APPLICATIONS_UPDATE = "/api/applications/update"
API_APPLICATIONS_SHOW = "/api/applications/show"
API_APPLICATIONS_SET_TAGS = "/api/applications/set_tags"
API_APPLICATIONS_REMOVE_PROJECT = "/api/applications/remove_project"
API_APPLICATIONS_DELETE_BRANCH = "/api/applications/delete_branch"
API_APPLICATIONS_DELETE = "/api/applications/delete"
API_APPLICATIONS_CREATE_BRANCH = "/api/applications/create_branch"
API_APPLICATIONS_CREATE = "/api/applications/create"

API_EDITIONS_SET_LICENSE = "/api/editions/set_license"

API_VIEWS_SHOW = "/api/views/show"
API_VIEWS_LIST = "/api/views/list"
API_VIEWS_DEFINE = "/api/views/define"
API_VIEWS_CREATE = "/api/views/create"
API_VIEWS_UPDATE = "/api/views/update"
API_VIEWS_DELETE = "/api/views/delete"
API_VIEWS_MOVE = "/api/views/move"
API_VIEWS_DEFINITION = "/api/views/definition"
API_VIEWS_SET_TAGS_MODE = "/api/views/set_tags_mode"
API_VIEWS_SET_NONE_MODE = "/api/views/set_none_mode"
API_VIEWS_SET_REGEXP_MODE = "/api/views/set_regexp_mode"
API_VIEWS_SET_MANUAL_MODE = "/api/views/set_manual_mode"
API_VIEWS_SET_REMAINING_PROJECTS_MODE = "/api/views/set_remaining_projects_mode"
API_VIEWS_MOVE_OPTIONS = "/api/views/move_options"
API_VIEWS_ADD_SUB_VIEW = "/api/views/add_sub_view"
API_VIEWS_ADD_PROJECT = "/api/views/add_project"
API_VIEWS_REMOVE_PROJECT = "/api/views/remove_project"
API_VIEWS_LOCAL_VIEWS = "/api/views/local_views"
API_VIEWS_ADD_LOCAL_VIEW = "/api/views/add_local_view"
API_VIEWS_ADD_PROJECT_BRANCH = "/api/views/add_project_branch"
API_VIEWS_REMOVE_PROJECT_BRANCH = "/api/views/remove_project_branch"
API_VIEWS_ADD_APPLICATION_BRANCH = "/api/views/add_application_branch"
API_VIEWS_REMOVE_APPLICATION_BRANCH = "/api/views/remove_application_branch"
API_VIEWS_APPLICATIONS = "/api/views/applications"
API_VIEWS_ADD_APPLICATION = "/api/views/add_application"
API_VIEWS_REMOVE_APPLICATION = "/api/views/remove_application"
API_VIEWS_PORTFOLIOS = "/api/views/portfolios"
API_VIEWS_ADD_PORTFOLIO = "/api/views/add_portfolio"
API_VIEWS_REMOVE_PORTFOLIO = "/api/views/remove_portfolio"

API_HOTSPOTS_SHOW = "/api/hotspots/show"
API_HOTSPOTS_SEARCH = "/api/hotspots/search"
API_HOTSPOTS_CHANGE_STATUS = "/api/hotspots/change_status"

API_NEW_CODE_PERIODS_LIST = "/api/new_code_periods/list"
API_NEW_CODE_PERIODS_SHOW = "/api/new_code_periods/show"
API_NEW_CODE_PERIODS_SET = "/api/new_code_periods/set"
API_NEW_CODE_PERIODS_UNSET = "/api/new_code_periods/unset"

API_ANALYSIS_CACHE = "/api/analysis_cache/get"

API_AUDIT_LOGS_DOWNLOAD = "/api/audit_logs/download"

API_MONITORING_METRICS = "/api/monitoring/metrics"
